### ISSUE TITLE
ctags error `illegal option -- -`

### ISSUE THREAD

**Issue by buggymcbugfix** [tomtomjhj/coq.ctags#1]
Hi, thanks for this! Unfortunately I am having trouble getting it to run, perhaps you have an idea what I am doing wrong?

```
$ ctags --options=~/github/coq.ctags            
/Library/Developer/CommandLineTools/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```

**Comment by tomtomjhj** [comment]
It seems that you are using BSD ctags. coq.ctags only works with a recent version of [Universal Ctags](https://github.com/universal-ctags/ctags). `ctags --version` should print something like this:

```console
$ ctags --version
Universal Ctags 5.9.0(p5.9.20220828.0), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep  2 2022, 18:13:07
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +packcc, +optscript, +pcre2
```

**Comment by buggymcbugfix** [comment]
Indeed, the executable was being shadowed by another `ctags` on my path.

But it's still nod good, I need to figure out how to build it on macOS with the pcre2 feature. Sorry I'm bad at computers.

**Comment by buggymcbugfix** [comment]
Working fine now. I'll open a PR to update the docs.
